version: '3.8'

services:
  api:
    build: .
    container_name: minha_api
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=senha123
      - DB_NAME=meubanco
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

  db:
    image: mysql:8
    container_name: meu_mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=senha123
      - MYSQL_DATABASE=meubanco
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  mysql_data:
